version: "3.3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USER: book_manager
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: authorize

  session:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass 123
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/resources/prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

volumes:
  redis-data:
  redis-conf:

