
server.port: 8086

info.app:
  name: "book-store"
  version: 1.0


logging:
  level.org.hibernate:
    SQL: debug
    stat: DEBUG

javax.persistence.schema-generation:
      scripts:
        action: none


management.endpoints.web.exposure:
        include: "prometheus,health,info,metrics,diskSpace,ping"

spring:
#
#  mvc.view:
#    prefix: /WEB-INF/jsp/
#    suffix: .jsp
  application:
    name: athorize

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://127.0.0.1:5432/authorize"
    username: book_manager
    password: 123

    initialization-mode: ALWAYS
    schema: classpath:schemaDB.sql

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: none
    generate-ddl: false

  session:
    timeout: 1500s
    store-type: jdbc
    jdbc:
      initialize-schema: never

  mvc.pathmatch:
      matching-strategy: ant-path-matcher