
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring_actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.64:8086']

